-- Create characters table used by the application tests and runtime
CREATE TABLE IF NOT EXISTS characters (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	ascendancy1 VARCHAR(50),
	ascendancy2 VARCHAR(50),
	ascendancy3 VARCHAR(50),
	image VARCHAR(2048)
);

INSERT INTO characters (id, name, ascendancy1, ascendancy2, ascendancy3, image) VALUES
	(1, 'Warrior', 'Smith of Kitava', 'Titan', 'Warbringer', '/image/warrior.jpg'),
	(2, 'Sorceress', 'Storm Weaver', 'Chronomancer', 'Disciple of Varashta', '/image/sorceress.jpg'),
	(3, 'Ranger', 'Deadeye', 'Pathfinder', 'N/A', '/image/ranger.jpg'),
	(4, 'Witch', 'Blood Mage', 'Infernalist', 'Lich', '/image/witch.jpg'),
	(5, 'Mercenary', 'Witch Hunter', 'Gemling Legionnaire', 'Tactician', '/image/merc.jpg'),
	(6, 'Monk', 'Invoker', 'Acolyte of Chayula', 'N/A', '/image/monk.jpg'),
	(7, 'Huntress', 'Ritualist', 'Amazon', 'N/A', '/image/huntress.jpg'),
	(8, 'Druid', 'Oracle', 'Shaman', 'N/A', '/image/druid.jpg'),
	(9, 'Doryani', 'NPC', 'N/A', 'N/A', '/image/doryani.jpg'),
	(10, 'Asala', 'NPC', 'N/A', 'N/A', '/image/asala.jpg'),
	(11, 'Alva', 'NPC', 'N/A', 'N/A', '/image/alva.jpg'),
	(12, 'Trial Master', 'NPC', 'N/A', 'N/A', '/image/trialmaster.jpg');
