-- Create characters table used by the application tests and runtime
CREATE TABLE IF NOT EXISTS characters (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	ascendancy1 VARCHAR(50),
	ascendancy2 VARCHAR(50),
	ascendancy3 VARCHAR(50),
	image VARCHAR(2048)
);

INSERT INTO characters (id, name, ascendancy1, ascendancy2, ascendancy3, image) VALUES
	(1, 'Warrior', 'Smith of Kitava', 'Titan', 'Warbringer', '/image/warrior.jpg'),
	(2, 'Sorceress', 'Storm Weaver', 'Chronomancer', 'Disciple of Varashta', '/image/sorceress.jpg'),
	(3, 'Ranger', 'Deadeye', 'Pathfinder', 'N/A', '/image/ranger.jpg'),
	(4, 'Witch', 'Blood Mage', 'Infernalist', 'Lich', '/image/witch.jpg'),
	(5, 'Mercenary', 'Witch Hunter', 'Gemling Legionnaire', 'Tactician', '/image/merc.jpg'),
	(6, 'Monk', 'Invoker', 'Acolyte of Chayula', 'N/A', '/image/monk.jpg'),
	(7, 'Huntress', 'Ritualist', 'Amazon', 'N/A', '/image/huntress.png'),
	(8, 'Druid', 'Oracle', 'Shaman', 'N/A', '/image/druid.jpeg'),
	(9, 'Barron', 'NPC', 'N/A', 'N/A', '/image/barron.jpg'),
	(10, 'Asala', 'NPC', 'N/A', 'N/A', '/image/asala.jpg'),
	(11, 'Maraketh Lieutenant', 'NPC', 'N/A', 'N/A', '/image/marakethlieutenant.jpg'),
	(12, 'Perrenial King', 'NPC', 'N/A', 'N/A', '/image/perrenialking.jpg');

ALTER TABLE characters ALTER COLUMN id RESTART WITH 13;
